Integration tests
cap-js/sdm pull request #20
Opened 2024-06-06 05:11 UTC by rishikunnath2747

Jira Link: https://jira.tools.sap/browse/SDMEXT-402
This PR is to set up automation testing for all the test cases using the integration testing framework established earlier.
Link to test cases: https://wiki.one.int.sap/wiki/display/sapecm/Test+Cases

2024-06-06 10:30 UTC, yashmeet29 requested changes
Rmove all .DS_Store files

2024-06-07 05:06 UTC, yashmeet29 approved these changes

2024-06-10 04:51 UTC, dheerasameerk commented on test/integration/api.js
> +        localConfig = JSON.parse(JSON.stringify(this.config));
This is used in all the methods. Can you set it in constructor and use it wherever required?

2024-06-10 05:09 UTC, dheerasameerk approved these changes
One small change

2024-06-11 05:53 UTC, rashmiangadi11 approved these changes

2024-06-11 06:02 UTC, yashmeet29 approved these changes

2024-06-11 07:58 UTC, merged